name: Package
run-name: Packaging of ${{  github.ref_name }} 📦
on: [push]
jobs:
  Prepare-Package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Build package
        run: |
          cd ${{ github.workspace }} && make

      - name: Create new release for ${{ github.ref }} 🚀
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: ${{ github.workspace }}/Portable-VSCode-linux-x64.zip, ${{ github.workspace }}/install.sh
          bodyFile: "manifest.md"

      - run: echo "💡 This job's status is ${{ job.status }}."
